### ISSUE TITLE
Remove illegally acquired email addresses!

### ISSUE THREAD

**Issue by ppeterka** [zhquan/TFG#1]
Remove illegally published email addresses!

**Comment by jgbarah** [comment]
Hi @ppeterka 
It seems that accidentally some email addresses ended in some files in this repository. We are working to remove those files asap.
Sorry for the inconvenience.

**Comment by jgbarah** [comment]
Already removed from the head of the branch.

**Comment by jgbarah** [comment]
I guess it is removed from all the git history now. @ppeterka please let us know if we can close this issue, please.

**Comment by jgbarah** [comment]
Closing, since no feedback was received. Feel free to reopen if anything else is needed to be done.
